version: "2"
services:
  lib: 
    build: ./
    image: lib
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/lib-db
      - PORT=3000   
  db:
    image: postgres
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=lib-db
      - DB_HOST=localhost